[package]
name = "rusty-elephant"
version = "0.1.0"
authors = ["Christopher Hotchkiss <christopher.hotchkiss@gmail.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.3.1"
bytes = "1.0.1"
tokio = { version = "1", features = ["full"] }
#threadpool = "1.8.1"
#sm = "0.9.0"