[package]
name = "rusty-elephant"
version = "0.1.0"
authors = ["Christopher Hotchkiss <christopher.hotchkiss@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.6"
tokio = { version = "0.3", features = ["full"] }
#threadpool = "1.8.1"
#sm = "0.9.0"